FROM busybox

WORKDIR /tmp/learningBase

COPY data/train/training_data.csv /tmp/learningBase/train/training_data.csv
COPY data/validation/test_data.csv /tmp/learningBase/validation/test_data.csv
COPY Readme.md /tmp/learningBase/Readme.md
